### ISSUE TITLE
SSL Error while trying to use this gem

### ISSUE THREAD

**Issue by collegeimprovements** [relrod/bing_translator-gem#22]
Hi, I followed all the steps in the documentation but I still keep getting this SSL Error. Is there any workaround for this?
```ruby
spanish_trans.rb:4: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bing_translator-4.4.1/lib/bing_translator.rb:164:in `rescue in result': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (BingTranslator::Exception)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bing_translator-4.4.1/lib/bing_translator.rb:158:in `result'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bing_translator-4.4.1/lib/bing_translator.rb:45:in `translate'
        from spanish_trans.rb:12:in `<main>'
```

**Comment by collegeimprovements** [comment]
I'm able to resolve this issue by providing `skip_ssl_verify = true` option in arguments list.
Sorry for the the issue. But I'm still keeping this for easy reference for other developers.
This is an excellent gem.
