### ISSUE TITLE
The received token is of incorrect token type. : ID=0261.V2_Soap.Translate.2BE299C8

### ISSUE THREAD

**Issue by Dariusch** [relrod/bing_translator-gem#34]
Hey guys, I ran into a Problem trying to translate a text.
```
translator = BingTranslator.new('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')
translator.translate('test', from: :de, to: :en)
```
returns
```
BingTranslator::Exception: (s:Client) ArgumentException: The received token is of incorrect token type. : ID=0261.V2_Soap.Translate.2BE299C8
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/bing_translator-5.0.0/lib/bing_translator.rb:152:in `rescue in result'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/bing_translator-5.0.0/lib/bing_translator.rb:150:in `result'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/bing_translator-5.0.0/lib/bing_translator.rb:38:in `translate'
	from (irb):16
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dochlast/projects/buddy/bin/rails:9:in `<top (required)>'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dochlast/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/dochlast/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dochlast/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Any1 else running into this issue? How can we solve this? And is Azure really a SOAP Endpoint, not a REST Endpoint? And why are specs failing?

**Comment by Dariusch** [comment]
Nevermind.. I ran into a trap.
Can you please update the readme and tell the world to use either Key1 or Key2 from
resource management -> keys?
